version: '2'

networks:
    core:
        external:
            name: core_core

services:

    webAdmin:
        build:
            context: ./webAdmin
            dockerfile: ./docker/Dockerfile
        ports:
            - '11004:80'
        volumes:
            - ./webAdmin:/srv/app
        external_links:
            - xml
        networks:
            - core


